name: release-please
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          manifest-file: ".github/.release-please-manifest.json"
          config-file: ".github/release-please-config.json"
